config/routes.rb
Rails.application.routes.draw do
  get "products/new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    # layout 'home'

    def dashboard
        render template: "home/dashboard_no_layout", layout: false
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def new
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/dashboard.html.erb
<%= content_for :h2, "Dashboard" %>
<%= link_to "New Product", products_new_path %>

<% content_for :navbar do %>
  <ul>
    <li>Ha</li>
    <li>He</li>
    <li>Hi</li>
    <li>Ho</li>
    <li>Hu</li>
  </ul>
<% end %>

app/views/home/dashboard_no_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InOut - home.html.erb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
    .nav-bar ul {
      display: inline-block;
    }

    .nav-bar ul li {
      float: left;
      width: 120px;
      background-color: pink;
      border: 1px solid #abcdef;
    }
    </style>
  </head>

  <body>
    <fieldset>
    <h2>Dashboard no layout</h2>

      <legend> Controller: <%= params[:controller] %>, Action: <%= params[:action] %> </legend>
      <%= link_to "New Product", products_new_path %>
    </fieldset>
    <div class="nav-bar">
      <ul>
        <li>Ha</li>
        <li>He</li>
        <li>Hi</li>
        <li>Ho</li>
        <li>Hu</li>
      </ul>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InOut</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <fieldset>
    <legend> Controller: <%= params[:controller] %>, Action: <%= params[:action] %> </legend>
    <%= yield %>
    </fieldset>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InOut - home.html.erb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
    .nav-bar ul {
      display: inline-block;
    }

    .nav-bar ul li {
      float: left;
      width: 120px;
      background-color: pink;
      border: 1px solid #abcdef;
    }
    </style>
  </head>

  <body>
    <div class="nav-bar">
      <%= yield :navbar %>
    </div>
    <fieldset>
    <h2><%= yield :h2 %></h2>

    <legend> Controller: <%= params[:controller] %>, Action: <%= params[:action] %> </legend>
    <%= yield %>

    </fieldset>

  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>

<dl>
<dt>requests</dt> <dd> <%= debug @request_ko %> </dd>
<dt>params</dt> <dd> <%= debug @my_params %> </dd>
</dl>
<h2> Mag-edit ka naman! Pang ilan? </h2>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/new.html.erb
<h2> hello world </h2>
    <%= link_to "Home", root_path %>